site_name: Prologue
site_description:  Medium scale Web Framework.

theme:
    name: 'material'

repo_name: planety/prologue
repo_url: https://github.com/planety/prologue
edit_uri: ""

nav:
    - Introduction: "index.md"
    - QuickStart: "quickstart.md"
    - Application: "application.md"
    - Requests: "requests.md"
    - Response: "response.md"
    - Route: "route.md"
    - Middleware: "middleware.md"
    - Static Files: "staticfiles.md"


markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - mkautodoc
